
name: MLflow CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        pip install mlflow==2.19.0 scikit-learn==1.5.2 pandas nltk Sastrawi

    - name: Run MLflow project
      run: |
        mlflow run .
